package com.itrex.maklerplus.collector.entity;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "advertMessages")
public class AdvertMessage {

  @Id private String id; // id generated by MongoDB

  private String nativeId; // id from message provider API

  private String chatId;

  private String text;

  private long nativeCreatedTime;

  private HostAPIEnum hostAPIEnum;

  private StatusEnum status = StatusEnum.IN_PROCESS;

  private String respCode;

  private byte attemptsCount = 1;

  private long createdTime = System.currentTimeMillis();
}
