package com.itrex.maklerplus.collector.entity;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "advertMessages")
public class AdvertMessage {

  @Id private String id; // id generated by MongoDB

  private String nativeId; // id from message provider API

  private String chatId;

  private String text;

  private long date;

  private HostAPIEnum hostAPIEnum;
}
